### PR TITLE
Add login page and the ability to logout

### PR DESCRIPTION
**Pull request by sebbonnet**
- add login page that redirects to index.html on successful login or displays the response content on error
- add logout link to the sidebar that redirects to the login.html on success or displays an error message
- update bower dependencies to point to an available startbootstrap-sb-admin-2

### CODE REVIEW

**Comment by spodkowinski** [comment]
Thanks for the PR! Can you also explain how the actual login is supposed to work from the backend side? Did you modify the reaper sources for that?

**Comment by sebbonnet** [comment]
- on the backend, 2 new endpoints are exposed to authenticate users and manage the session
  - /login (POST) that takes a username and password and authenticates the user. This would create the session on success
  - /logout (POST) which should invalidate the session
  - api users need to provide a configuration file (shiro.ini) to define protected resources (urls), login page, allowed users and other authentication configuration. Protected resources will redirect requests to the login page when accessed without login, according to the shiro configuration. Public resources can be accessed without login
- on the client, the session is maintained on the client via a session cookie

I have extended the reaper backend to support authentication using Apache Shiro and enabled session management in the servlet container (not Shiro's session management). See here: spotify/cassandra-reaper#146
This does not pass the build at the moment unfortunately as the PR is based on java8, yet the build supports only java7. I'm hoping they upgrade the build to java8 soon if not i'll to revise the PR.

**Comment by spodkowinski** [comment]
I've applied two of your bug fixes to master and going to keep this PR open until your PR in the reaper server has been merged. Until then I like to keep `cassandra-reaper-ui/master` feature compatible with `cassandra-reaper/master`.

**Comment by joelsdc** [comment]
I'm pretty sure cassandra-reaper-0.5.0 is based on java 8. I had to install it to get it to compile, as with java 7 it would fail. 

Maybe it's time to revisit this?

**Pull request closed without merging**
